apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: cluster.clusterincluster.k8s.io
  # for more information on the below annotation, please see
  # https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/2337-k8s.io-group-protection/README.md
  annotations:
    "api-approved.kubernetes.io": "unapproved, experimental-only; please get an approval from Kubernetes API reviewers if you're trying to develop a CRD in the *.k8s.io or *.kubernetes.io groups"
spec:
  group: clusterincluster.k8s.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        # schema used for validation
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                clusterName:
                  type: string
                aciSubscriptionId:
                  type: string
                aciResourceGroup:
                  type: string
                vnetSubscriptionId:
                  type: string
                vnetResourceGroup:
                  type: string
                vnetName:
                  type: string
                subnetName:
                  type: string
            status:
              type: object
              properties:
                state:
                  type: string
  names:
    kind: Cluster
    plural: clusters
    categories:
      - all
  scope: Namespaced
